# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact_info_simple.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_USGSContactInfoWidget(object):
    def setupUi(self, USGSContactInfoWidget):
        USGSContactInfoWidget.setObjectName(_fromUtf8("USGSContactInfoWidget"))
        USGSContactInfoWidget.resize(528, 312)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        USGSContactInfoWidget.setFont(font)
        USGSContactInfoWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        USGSContactInfoWidget.setAcceptDrops(True)
        USGSContactInfoWidget.setStyleSheet(_fromUtf8("QLabel{\n"
"font: 9pt \"Arial\";\n"
"color: rgb(90, 90, 90);\n"
"}\n"
"\n"
"QLineEdit {\n"
"font: 9pt \"Arial\";\n"
"color: rgb(50, 50, 50);\n"
"}"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(USGSContactInfoWidget)
        self.verticalLayout_11.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_11.setContentsMargins(4, 0, 4, 4)
        self.verticalLayout_11.setSpacing(4)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_7.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        spacerItem = QtGui.QSpacerItem(40, 0, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem)
        self.btn_import_contact = QtGui.QPushButton(USGSContactInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import_contact.sizePolicy().hasHeightForWidth())
        self.btn_import_contact.setSizePolicy(sizePolicy)
        self.btn_import_contact.setMinimumSize(QtCore.QSize(140, 0))
        self.btn_import_contact.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_import_contact.setObjectName(_fromUtf8("btn_import_contact"))
        self.horizontalLayout_17.addWidget(self.btn_import_contact)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.groupBox_2 = QtGui.QGroupBox(USGSContactInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setStyleSheet(_fromUtf8(""))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setMargin(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8(""))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(0)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cntper = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntper.sizePolicy().hasHeightForWidth())
        self.cntper.setSizePolicy(sizePolicy)
        self.cntper.setMinimumSize(QtCore.QSize(217, 0))
        self.cntper.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntper.setText(_fromUtf8(""))
        self.cntper.setPlaceholderText(_fromUtf8(""))
        self.cntper.setObjectName(_fromUtf8("cntper"))
        self.horizontalLayout.addWidget(self.cntper)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(15, 0))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setIndent(0)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cntorg = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntorg.sizePolicy().hasHeightForWidth())
        self.cntorg.setSizePolicy(sizePolicy)
        self.cntorg.setMinimumSize(QtCore.QSize(0, 0))
        self.cntorg.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntorg.setObjectName(_fromUtf8("cntorg"))
        self.horizontalLayout_3.addWidget(self.cntorg)
        spacerItem1 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cntpos = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntpos.sizePolicy().hasHeightForWidth())
        self.cntpos.setSizePolicy(sizePolicy)
        self.cntpos.setMinimumSize(QtCore.QSize(0, 0))
        self.cntpos.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntpos.setObjectName(_fromUtf8("cntpos"))
        self.horizontalLayout_4.addWidget(self.cntpos)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(0, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.cntvoice = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntvoice.sizePolicy().hasHeightForWidth())
        self.cntvoice.setSizePolicy(sizePolicy)
        self.cntvoice.setMinimumSize(QtCore.QSize(0, 0))
        self.cntvoice.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntvoice.setObjectName(_fromUtf8("cntvoice"))
        self.horizontalLayout_5.addWidget(self.cntvoice)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(15, 0))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_7.setIndent(0)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_5.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(0, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_9.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.cntfax = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntfax.sizePolicy().hasHeightForWidth())
        self.cntfax.setSizePolicy(sizePolicy)
        self.cntfax.setMinimumSize(QtCore.QSize(0, 0))
        self.cntfax.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntfax.setObjectName(_fromUtf8("cntfax"))
        self.horizontalLayout_6.addWidget(self.cntfax)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMinimumSize(QtCore.QSize(0, 0))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setStyleSheet(_fromUtf8(""))
        self.label_18.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout.addWidget(self.label_18)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.cntemail = QtGui.QLineEdit(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cntemail.sizePolicy().hasHeightForWidth())
        self.cntemail.setSizePolicy(sizePolicy)
        self.cntemail.setMinimumSize(QtCore.QSize(0, 0))
        self.cntemail.setMaximumSize(QtCore.QSize(16777215, 20))
        self.cntemail.setObjectName(_fromUtf8("cntemail"))
        self.horizontalLayout_7.addWidget(self.cntemail)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_14.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(USGSContactInfoWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setStyleSheet(_fromUtf8(""))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setMargin(6)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet(_fromUtf8(""))
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_19.setWordWrap(False)
        self.label_19.setIndent(0)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.address = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address.sizePolicy().hasHeightForWidth())
        self.address.setSizePolicy(sizePolicy)
        self.address.setMinimumSize(QtCore.QSize(0, 0))
        self.address.setMaximumSize(QtCore.QSize(16777215, 20))
        self.address.setObjectName(_fromUtf8("address"))
        self.horizontalLayout_8.addWidget(self.address)
        self.label_20 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(15, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setIndent(0)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 0))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_5.addWidget(self.label_21)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.address2 = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address2.sizePolicy().hasHeightForWidth())
        self.address2.setSizePolicy(sizePolicy)
        self.address2.setMinimumSize(QtCore.QSize(0, 0))
        self.address2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.address2.setObjectName(_fromUtf8("address2"))
        self.horizontalLayout_9.addWidget(self.address2)
        spacerItem5 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        self.label_22.setMinimumSize(QtCore.QSize(0, 0))
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_22.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.address3 = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address3.sizePolicy().hasHeightForWidth())
        self.address3.setSizePolicy(sizePolicy)
        self.address3.setMinimumSize(QtCore.QSize(0, 0))
        self.address3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.address3.setObjectName(_fromUtf8("address3"))
        self.horizontalLayout_10.addWidget(self.address3)
        spacerItem6 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_23 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        self.label_23.setMinimumSize(QtCore.QSize(0, 0))
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_23.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.verticalLayout_5.addWidget(self.label_23)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.city = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city.sizePolicy().hasHeightForWidth())
        self.city.setSizePolicy(sizePolicy)
        self.city.setMinimumSize(QtCore.QSize(0, 0))
        self.city.setMaximumSize(QtCore.QSize(16777215, 20))
        self.city.setObjectName(_fromUtf8("city"))
        self.horizontalLayout_11.addWidget(self.city)
        self.label_24 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        self.label_24.setMinimumSize(QtCore.QSize(15, 20))
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setScaledContents(True)
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setIndent(0)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_11.addWidget(self.label_24)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_27 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMinimumSize(QtCore.QSize(0, 0))
        self.label_27.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_27.setStyleSheet(_fromUtf8(""))
        self.label_27.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_8.addWidget(self.label_27)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.state = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state.sizePolicy().hasHeightForWidth())
        self.state.setSizePolicy(sizePolicy)
        self.state.setMinimumSize(QtCore.QSize(0, 0))
        self.state.setMaximumSize(QtCore.QSize(16777215, 20))
        self.state.setObjectName(_fromUtf8("state"))
        self.horizontalLayout_18.addWidget(self.state)
        self.label_28 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(15, 0))
        self.label_28.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setScaledContents(True)
        self.label_28.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_28.setIndent(0)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_18.addWidget(self.label_28)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_8)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_30 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_30.sizePolicy().hasHeightForWidth())
        self.label_30.setSizePolicy(sizePolicy)
        self.label_30.setMinimumSize(QtCore.QSize(0, 0))
        self.label_30.setMaximumSize(QtCore.QSize(75, 20))
        self.label_30.setStyleSheet(_fromUtf8(""))
        self.label_30.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_2.addWidget(self.label_30)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.postal = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postal.sizePolicy().hasHeightForWidth())
        self.postal.setSizePolicy(sizePolicy)
        self.postal.setMinimumSize(QtCore.QSize(0, 0))
        self.postal.setMaximumSize(QtCore.QSize(75, 20))
        self.postal.setObjectName(_fromUtf8("postal"))
        self.horizontalLayout_2.addWidget(self.postal)
        self.label_29 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMinimumSize(QtCore.QSize(15, 0))
        self.label_29.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setScaledContents(True)
        self.label_29.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_29.setIndent(0)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_2.addWidget(self.label_29)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_19.addLayout(self.verticalLayout_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setSpacing(2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.label_31 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setMinimumSize(QtCore.QSize(0, 0))
        self.label_31.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_31.setStyleSheet(_fromUtf8(""))
        self.label_31.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_9.addWidget(self.label_31)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setSpacing(2)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.country = QtGui.QLineEdit(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.country.sizePolicy().hasHeightForWidth())
        self.country.setSizePolicy(sizePolicy)
        self.country.setMinimumSize(QtCore.QSize(0, 0))
        self.country.setMaximumSize(QtCore.QSize(16777215, 20))
        self.country.setBaseSize(QtCore.QSize(25, 0))
        self.country.setObjectName(_fromUtf8("country"))
        self.horizontalLayout_21.addWidget(self.country)
        self.verticalLayout_9.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_20.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSpacing(2)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.label_33 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_33.sizePolicy().hasHeightForWidth())
        self.label_33.setSizePolicy(sizePolicy)
        self.label_33.setMinimumSize(QtCore.QSize(0, 0))
        self.label_33.setMaximumSize(QtCore.QSize(75, 20))
        self.label_33.setStyleSheet(_fromUtf8(""))
        self.label_33.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_10.addWidget(self.label_33)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.addrtype = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addrtype.sizePolicy().hasHeightForWidth())
        self.addrtype.setSizePolicy(sizePolicy)
        self.addrtype.setMinimumSize(QtCore.QSize(0, 0))
        self.addrtype.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.addrtype.setEditable(True)
        self.addrtype.setObjectName(_fromUtf8("addrtype"))
        self.addrtype.addItem(_fromUtf8(""))
        self.addrtype.addItem(_fromUtf8(""))
        self.addrtype.addItem(_fromUtf8(""))
        self.horizontalLayout_12.addWidget(self.addrtype)
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setMinimumSize(QtCore.QSize(15, 20))
        self.label_34.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_34.setFont(font)
        self.label_34.setScaledContents(True)
        self.label_34.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_34.setIndent(0)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_12.addWidget(self.label_34)
        self.verticalLayout_10.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_20.addLayout(self.verticalLayout_10)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.horizontalLayout_14.addWidget(self.groupBox_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.verticalLayout_11.addLayout(self.verticalLayout_7)
        self.label_27.raise_()
        self.state.raise_()
        self.label_28.raise_()
        self.postal.raise_()
        self.label_29.raise_()
        self.label_30.raise_()

        self.retranslateUi(USGSContactInfoWidget)
        QtCore.QMetaObject.connectSlotsByName(USGSContactInfoWidget)

    def retranslateUi(self, USGSContactInfoWidget):
        USGSContactInfoWidget.setWindowTitle(_translate("USGSContactInfoWidget", "Form", None))
        self.btn_import_contact.setToolTip(_translate("USGSContactInfoWidget", "Import contact information from USGS Active Directory", None))
        self.btn_import_contact.setText(_translate("USGSContactInfoWidget", "Import USGS Contact", None))
        self.label_2.setToolTip(_translate("USGSContactInfoWidget", "The name of the person to contact", None))
        self.label_2.setText(_translate("USGSContactInfoWidget", "Contact Person", None))
        self.cntper.setToolTip(_translate("USGSContactInfoWidget", "Contact Person -- the name of the individual to which the contact type applies.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntper", None))
        self.label_3.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_3.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_4.setText(_translate("USGSContactInfoWidget", "Organization Name", None))
        self.cntorg.setToolTip(_translate("USGSContactInfoWidget", "Contact Organization -- the name of the organization to which the contact type applies.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntorg", None))
        self.label_5.setText(_translate("USGSContactInfoWidget", "Title of Position", None))
        self.cntpos.setToolTip(_translate("USGSContactInfoWidget", "Contact Position -- the title of individual.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntpos", None))
        self.label_8.setText(_translate("USGSContactInfoWidget", "Telephone Number", None))
        self.cntvoice.setToolTip(_translate("USGSContactInfoWidget", "Contact Voice Telephone -- the telephone number by which individuals can speak to the\n"
"organization or individual.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntvoice", None))
        self.label_7.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_7.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_9.setText(_translate("USGSContactInfoWidget", "Fax Number", None))
        self.cntfax.setToolTip(_translate("USGSContactInfoWidget", "Contact Facsimile Telephone -- the telephone number of a facsimile machine of the organization or\n"
"individual.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntfax", None))
        self.label_18.setText(_translate("USGSContactInfoWidget", "Email Address", None))
        self.cntemail.setToolTip(_translate("USGSContactInfoWidget", "Contact Electronic Mail Address -- the address of the electronic mailbox of the organization or\n"
"individual.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: cntemail", None))
        self.label_19.setText(_translate("USGSContactInfoWidget", "Address 1 (Number of Street)", None))
        self.address.setToolTip(_translate("USGSContactInfoWidget", "Address -- an address line for the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: address", None))
        self.label_20.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_20.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_21.setText(_translate("USGSContactInfoWidget", "Address 2 (if Applicable)", None))
        self.address2.setToolTip(_translate("USGSContactInfoWidget", "Address -- an address line for the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: address", None))
        self.label_22.setText(_translate("USGSContactInfoWidget", "Address 3 (if Applicable) ", None))
        self.address3.setToolTip(_translate("USGSContactInfoWidget", "Address -- an address line for the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: address", None))
        self.label_23.setText(_translate("USGSContactInfoWidget", "City", None))
        self.city.setToolTip(_translate("USGSContactInfoWidget", "City -- the city of the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: city", None))
        self.label_24.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_24.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_27.setText(_translate("USGSContactInfoWidget", "State / Province", None))
        self.state.setToolTip(_translate("USGSContactInfoWidget", "State or Province -- the state or province of the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: state\n"
"", None))
        self.label_28.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_28.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_30.setText(_translate("USGSContactInfoWidget", "Zipcode", None))
        self.postal.setToolTip(_translate("USGSContactInfoWidget", "Postal Code -- the ZIP or other postal code of the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: postal\n"
"", None))
        self.label_29.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_29.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))
        self.label_31.setText(_translate("USGSContactInfoWidget", "Country", None))
        self.country.setToolTip(_translate("USGSContactInfoWidget", "Country -- the country of the address.\n"
"Type: text\n"
"Domain: free text\n"
"Short Name: country", None))
        self.label_33.setText(_translate("USGSContactInfoWidget", "Address Type", None))
        self.addrtype.setToolTip(_translate("USGSContactInfoWidget", "Address Type -- the information provided by the address.\n"
"Type: text\n"
"Domain: \"mailing\" \"physical\" \"mailing and physical\", free text\n"
"Short Name: addrtype\n"
"", None))
        self.addrtype.setItemText(0, _translate("USGSContactInfoWidget", "Mailing", None))
        self.addrtype.setItemText(1, _translate("USGSContactInfoWidget", "Physical", None))
        self.addrtype.setItemText(2, _translate("USGSContactInfoWidget", "Mailing and Physical", None))
        self.label_34.setToolTip(_translate("USGSContactInfoWidget", "Required", None))
        self.label_34.setText(_translate("USGSContactInfoWidget", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>", None))

