# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Citation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1017, 240)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fgdc_citeinfo = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_citeinfo.sizePolicy().hasHeightForWidth())
        self.fgdc_citeinfo.setSizePolicy(sizePolicy)
        self.fgdc_citeinfo.setMinimumSize(QtCore.QSize(0, 220))
        self.fgdc_citeinfo.setObjectName("fgdc_citeinfo")
        self.fgdc_title = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_title.setGeometry(QtCore.QRect(20, 70, 901, 20))
        self.fgdc_title.setObjectName("fgdc_title")
        self.label = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 731, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 161, 21))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 361, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_5.setGeometry(QtCore.QRect(410, 90, 181, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_6.setGeometry(QtCore.QRect(410, 110, 261, 200))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 200))
        self.label_6.setObjectName("label_6")
        self.fgdc_origin = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_origin.setGeometry(QtCore.QRect(20, 130, 361, 20))
        self.fgdc_origin.setObjectName("fgdc_origin")
        self.fgdc_pubdate = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_pubdate.setGeometry(QtCore.QRect(410, 130, 211, 20))
        self.fgdc_pubdate.setObjectName("fgdc_pubdate")
        self.label_7 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_7.setGeometry(QtCore.QRect(20, 180, 361, 16))
        self.label_7.setObjectName("label_7")
        self.groupBox = QtWidgets.QGroupBox(self.fgdc_citeinfo)
        self.groupBox.setGeometry(QtCore.QRect(280, 180, 101, 21))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 0, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(60, 0, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_8 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_8.setGeometry(QtCore.QRect(400, 180, 451, 21))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_9.setGeometry(QtCore.QRect(690, 90, 161, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.lineEdit.setGeometry(QtCore.QRect(690, 130, 181, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_10 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_10.setGeometry(QtCore.QRect(690, 110, 301, 16))
        self.label_10.setObjectName("label_10")
        self.fgdc_title.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.fgdc_origin.raise_()
        self.fgdc_pubdate.raise_()
        self.label_7.raise_()
        self.groupBox.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.radioButton.raise_()
        self.lineEdit.raise_()
        self.label_10.raise_()
        self.verticalLayout.addWidget(self.fgdc_citeinfo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_citeinfo.setTitle(_translate("Form", "Citation"))
        self.label.setText(_translate("Form", "Data Set Title"))
        self.label_2.setText(_translate("Form", "A good title includes \'What\', \'Where\', and \'When\'.  (Example: Point Locations of Wind Turbines in Colorado, Derived from 2010 NAIP Imagery"))
        self.label_3.setText(_translate("Form", "Data Set Author / Originator"))
        self.label_4.setText(_translate("Form", "Who created the data set? List the organization and/or person(s)"))
        self.label_5.setText(_translate("Form", "Publication Date (YYYYMMDD)"))
        self.label_6.setText(_translate("Form", "When was the data set published or finalized?"))
        self.label_7.setText(_translate("Form", "Is this data set associated with a larger work?"))
        self.radioButton.setText(_translate("Form", "Yes"))
        self.radioButton_2.setText(_translate("Form", "No"))
        self.label_8.setText(_translate("Form", "If the citation of a larger project is relevant, you may optionally cite it here."))
        self.label_9.setText(_translate("Form", "Online Link for the Data Set"))
        self.label_10.setText(_translate("Form", "Is there a link to the data or agency that produced it?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

