# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Citation.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1126, 774)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.formLayout_2 = QtWidgets.QFormLayout(Form)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fgdc_citeinfo = QtWidgets.QGroupBox(Form)
        self.fgdc_citeinfo.setMinimumSize(QtCore.QSize(1000, 360))
        self.fgdc_citeinfo.setObjectName("fgdc_citeinfo")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fgdc_citeinfo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_33 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_2.addWidget(self.label_33)
        self.label_34 = QtWidgets.QLabel(self.fgdc_citeinfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_2.addWidget(self.label_34)
        self.fgdc_title = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_title.setObjectName("fgdc_title")
        self.verticalLayout_2.addWidget(self.fgdc_title)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_14 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.fgdc_geoform = QtWidgets.QComboBox(self.fgdc_citeinfo)
        self.fgdc_geoform.setEditable(True)
        self.fgdc_geoform.setObjectName("fgdc_geoform")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.verticalLayout.addWidget(self.fgdc_geoform)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_35 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_18.addWidget(self.label_35)
        self.label_36 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_18.addWidget(self.label_36)
        self.fgdc_origin = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_origin.setObjectName("fgdc_origin")
        self.verticalLayout_18.addWidget(self.fgdc_origin)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_37 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_19.addWidget(self.label_37)
        self.label_38 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_19.addWidget(self.label_38)
        self.fgdc_pubdate = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_pubdate.setObjectName("fgdc_pubdate")
        self.verticalLayout_19.addWidget(self.fgdc_pubdate)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_39 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_20.addWidget(self.label_39)
        self.label_40 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_20.addWidget(self.label_40)
        self.fgdc_onlink = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_onlink.setObjectName("fgdc_onlink")
        self.verticalLayout_20.addWidget(self.fgdc_onlink)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_23 = QtWidgets.QLabel(self.fgdc_citeinfo)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_3.addWidget(self.label_23)
        self.fgdc_edition = QtWidgets.QLineEdit(self.fgdc_citeinfo)
        self.fgdc_edition.setObjectName("fgdc_edition")
        self.verticalLayout_3.addWidget(self.fgdc_edition)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.fgdc_serinfo = QtWidgets.QGroupBox(self.fgdc_citeinfo)
        self.fgdc_serinfo.setTitle("")
        self.fgdc_serinfo.setObjectName("fgdc_serinfo")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.fgdc_serinfo)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_43 = QtWidgets.QLabel(self.fgdc_serinfo)
        self.label_43.setObjectName("label_43")
        self.horizontalLayout_6.addWidget(self.label_43)
        spacerItem = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.radioButton_3 = QtWidgets.QRadioButton(self.fgdc_serinfo)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.fgdc_serinfo)
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_6.addWidget(self.radioButton_4)
        self.verticalLayout_23.addLayout(self.horizontalLayout_6)
        self.label_44 = QtWidgets.QLabel(self.fgdc_serinfo)
        self.label_44.setObjectName("label_44")
        self.verticalLayout_23.addWidget(self.label_44)
        self.series_ext = QtWidgets.QFrame(self.fgdc_serinfo)
        self.series_ext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.series_ext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.series_ext.setObjectName("series_ext")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.series_ext)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_42 = QtWidgets.QLabel(self.series_ext)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_21.addWidget(self.label_42)
        self.fgdc_sername = QtWidgets.QLineEdit(self.series_ext)
        self.fgdc_sername.setObjectName("fgdc_sername")
        self.verticalLayout_21.addWidget(self.fgdc_sername)
        self.horizontalLayout_9.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_41 = QtWidgets.QLabel(self.series_ext)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_22.addWidget(self.label_41)
        self.fgdc_issue = QtWidgets.QLineEdit(self.series_ext)
        self.fgdc_issue.setObjectName("fgdc_issue")
        self.verticalLayout_22.addWidget(self.fgdc_issue)
        self.horizontalLayout_9.addLayout(self.verticalLayout_22)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        self.verticalLayout_23.addWidget(self.series_ext)
        self.horizontalLayout_21.addLayout(self.verticalLayout_23)
        self.horizontalLayout_30.addWidget(self.fgdc_serinfo)
        self.fgdc_pubinfo = QtWidgets.QGroupBox(self.fgdc_citeinfo)
        self.fgdc_pubinfo.setTitle("")
        self.fgdc_pubinfo.setObjectName("fgdc_pubinfo")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.fgdc_pubinfo)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_49 = QtWidgets.QLabel(self.fgdc_pubinfo)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_8.addWidget(self.label_49)
        spacerItem1 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.fgdc_pubinfo)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_8.addWidget(self.radioButton_5)
        self.radioButton_8 = QtWidgets.QRadioButton(self.fgdc_pubinfo)
        self.radioButton_8.setChecked(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout_8.addWidget(self.radioButton_8)
        self.verticalLayout_24.addLayout(self.horizontalLayout_8)
        self.label_50 = QtWidgets.QLabel(self.fgdc_pubinfo)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_24.addWidget(self.label_50)
        self.pub_ext = QtWidgets.QFrame(self.fgdc_pubinfo)
        self.pub_ext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pub_ext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pub_ext.setObjectName("pub_ext")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.pub_ext)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_51 = QtWidgets.QLabel(self.pub_ext)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_30.addWidget(self.label_51)
        self.fgdc_pubplace = QtWidgets.QLineEdit(self.pub_ext)
        self.fgdc_pubplace.setObjectName("fgdc_pubplace")
        self.verticalLayout_30.addWidget(self.fgdc_pubplace)
        self.horizontalLayout_12.addLayout(self.verticalLayout_30)
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_52 = QtWidgets.QLabel(self.pub_ext)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_31.addWidget(self.label_52)
        self.fgdc_publish = QtWidgets.QLineEdit(self.pub_ext)
        self.fgdc_publish.setObjectName("fgdc_publish")
        self.verticalLayout_31.addWidget(self.fgdc_publish)
        self.horizontalLayout_12.addLayout(self.verticalLayout_31)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_12)
        self.verticalLayout_24.addWidget(self.pub_ext)
        self.horizontalLayout_16.addLayout(self.verticalLayout_24)
        self.horizontalLayout_30.addWidget(self.fgdc_pubinfo)
        self.verticalLayout_4.addLayout(self.horizontalLayout_30)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.fgdc_lworkcit = QtWidgets.QGroupBox(self.fgdc_citeinfo)
        self.fgdc_lworkcit.setObjectName("fgdc_lworkcit")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.fgdc_lworkcit)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_63 = QtWidgets.QLabel(self.fgdc_lworkcit)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_27.addWidget(self.label_63)
        spacerItem2 = QtWidgets.QSpacerItem(48, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem2)
        self.radioButton = QtWidgets.QRadioButton(self.fgdc_lworkcit)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_27.addWidget(self.radioButton)
        self.radioButton_14 = QtWidgets.QRadioButton(self.fgdc_lworkcit)
        self.radioButton_14.setChecked(True)
        self.radioButton_14.setObjectName("radioButton_14")
        self.horizontalLayout_27.addWidget(self.radioButton_14)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_27)
        self.label_64 = QtWidgets.QLabel(self.fgdc_lworkcit)
        self.label_64.setObjectName("label_64")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_64)
        self.lworkcite_ext = QtWidgets.QFrame(self.fgdc_lworkcit)
        self.lworkcite_ext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lworkcite_ext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lworkcite_ext.setObjectName("lworkcite_ext")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.lworkcite_ext)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.lworkcit_ext = QtWidgets.QFrame(self.lworkcite_ext)
        self.lworkcit_ext.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lworkcit_ext.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lworkcit_ext.setObjectName("lworkcit_ext")
        self.horizontalLayout_3.addWidget(self.lworkcit_ext)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.lworkcite_ext)
        self.horizontalLayout_26.addLayout(self.formLayout)
        self.verticalLayout_5.addWidget(self.fgdc_lworkcit)
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.fgdc_citeinfo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_citeinfo.setTitle(_translate("Form", "Citation"))
        self.label_33.setText(_translate("Form", "Data Set Title"))
        self.label_34.setText(_translate("Form", "A good title includes \'What\', \'Where\', and \'When\'.  (Example: Point Locations of Wind Turbines in Colorado, Derived from 2010 NAIP Imagery)"))
        self.label_14.setText(_translate("Form", "Larger Work Format"))
        self.fgdc_geoform.setItemText(0, _translate("Form", "Publication (Book)"))
        self.fgdc_geoform.setItemText(1, _translate("Form", "Publication (Journal)"))
        self.fgdc_geoform.setItemText(2, _translate("Form", "Publication (Other)"))
        self.fgdc_geoform.setItemText(3, _translate("Form", "Ongoing Project"))
        self.fgdc_geoform.setItemText(4, _translate("Form", "Website"))
        self.fgdc_geoform.setItemText(5, _translate("Form", "GIS Data Project/Collection"))
        self.fgdc_geoform.setItemText(6, _translate("Form", "GIS Data Service"))
        self.fgdc_geoform.setItemText(7, _translate("Form", "Other"))
        self.label_35.setText(_translate("Form", "Data Set Author / Originator"))
        self.label_36.setText(_translate("Form", "Who created the data set? List the organization and/or person(s)"))
        self.label_37.setText(_translate("Form", "Publication Date (YYYYMMDD)"))
        self.label_38.setText(_translate("Form", "When was the data set published or finalized?"))
        self.label_39.setText(_translate("Form", "Online Link for the Data Set"))
        self.label_40.setText(_translate("Form", "Is there a link to the data or agency that produced it?"))
        self.label_23.setText(_translate("Form", "Edition"))
        self.label_43.setText(_translate("Form", "Is this data set part of a series?"))
        self.radioButton_3.setText(_translate("Form", "Yes"))
        self.radioButton_4.setText(_translate("Form", "No"))
        self.label_44.setText(_translate("Form", " Is it a release with an assigned issue number (e.g. USGS Data Series)"))
        self.label_42.setText(_translate("Form", "Series Name"))
        self.label_41.setText(_translate("Form", "Issue Name / Number within Series"))
        self.label_49.setText(_translate("Form", "Can you provide more publication information about this data set?"))
        self.radioButton_5.setText(_translate("Form", "Yes"))
        self.radioButton_8.setText(_translate("Form", "No"))
        self.label_50.setText(_translate("Form", "More details are always helpful for finding and properly referencing data."))
        self.label_51.setText(_translate("Form", "Publication Place"))
        self.label_52.setText(_translate("Form", "Publisher"))
        self.fgdc_lworkcit.setTitle(_translate("Form", "Larger Work"))
        self.label_63.setText(_translate("Form", "Is this data set associated with a larger work?"))
        self.radioButton.setText(_translate("Form", "Yes"))
        self.radioButton_14.setText(_translate("Form", "No"))
        self.label_64.setText(_translate("Form", "If the citation of a larger project is relevant, you may optionally cite it here."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

