# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'codesetd.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fgdc_codesetd(object):
    def setupUi(self, fgdc_codesetd):
        fgdc_codesetd.setObjectName("fgdc_codesetd")
        fgdc_codesetd.resize(418, 442)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(fgdc_codesetd.sizePolicy().hasHeightForWidth())
        fgdc_codesetd.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(fgdc_codesetd)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMinimumSize(QtCore.QSize(0, 0))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("")
        self.label_19.setScaledContents(False)
        self.label_19.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_19.setWordWrap(False)
        self.label_19.setIndent(0)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.fgdc_codesetn = QtWidgets.QComboBox(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_codesetn.sizePolicy().hasHeightForWidth())
        self.fgdc_codesetn.setSizePolicy(sizePolicy)
        self.fgdc_codesetn.setMinimumSize(QtCore.QSize(0, 0))
        self.fgdc_codesetn.setEditable(True)
        self.fgdc_codesetn.setObjectName("fgdc_codesetn")
        self.fgdc_codesetn.addItem("")
        self.fgdc_codesetn.addItem("")
        self.fgdc_codesetn.addItem("")
        self.fgdc_codesetn.addItem("")
        self.fgdc_codesetn.addItem("")
        self.fgdc_codesetn.addItem("")
        self.horizontalLayout_8.addWidget(self.fgdc_codesetn)
        self.label_20 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(15, 0))
        self.label_20.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setScaledContents(True)
        self.label_20.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_20.setIndent(0)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_8.addWidget(self.label_20)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.label_21 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMinimumSize(QtCore.QSize(0, 0))
        self.label_21.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_21.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_5.addWidget(self.label_21)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.fgdc_codesets = QtWidgets.QLineEdit(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_codesets.sizePolicy().hasHeightForWidth())
        self.fgdc_codesets.setSizePolicy(sizePolicy)
        self.fgdc_codesets.setMinimumSize(QtCore.QSize(0, 0))
        self.fgdc_codesets.setObjectName("fgdc_codesets")
        self.horizontalLayout_9.addWidget(self.fgdc_codesets)
        self.label_25 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(15, 20))
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setScaledContents(True)
        self.label_25.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_25.setIndent(0)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setStyleSheet("font: bold;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(fgdc_codesetd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setStyleSheet("font: italic;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(fgdc_codesetd)
        QtCore.QMetaObject.connectSlotsByName(fgdc_codesetd)

    def retranslateUi(self, fgdc_codesetd):
        _translate = QtCore.QCoreApplication.translate
        fgdc_codesetd.setWindowTitle(_translate("fgdc_codesetd", "Form"))
        self.label_19.setText(_translate("fgdc_codesetd", "Codeset Name"))
        self.fgdc_codesetn.setItemText(0, _translate("fgdc_codesetd", "FIPS Code (2-Digit State ID)"))
        self.fgdc_codesetn.setItemText(1, _translate("fgdc_codesetd", "FIPS Code (3-Digit County ID)"))
        self.fgdc_codesetn.setItemText(2, _translate("fgdc_codesetd", "FIPS Code (5-Digit State & County ID)"))
        self.fgdc_codesetn.setItemText(3, _translate("fgdc_codesetd", "US Postal Zip Codes"))
        self.fgdc_codesetn.setItemText(4, _translate("fgdc_codesetd", "US Postal 2-Letter State"))
        self.fgdc_codesetn.setItemText(5, _translate("fgdc_codesetd", "MAF / TIGER Feature Class Codes (MTFCC)"))
        self.label_20.setToolTip(_translate("fgdc_codesetd", "Required"))
        self.label_20.setText(_translate("fgdc_codesetd", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>"))
        self.label_21.setText(_translate("fgdc_codesetd", "Codeset Source"))
        self.label_25.setToolTip(_translate("fgdc_codesetd", "Required"))
        self.label_25.setText(_translate("fgdc_codesetd", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#55aaff;\">*</span></p></body></html>"))
        self.label_2.setText(_translate("fgdc_codesetd", "\"Codeset Domain\""))
        self.label_3.setText(_translate("fgdc_codesetd", "This attribute type should be used when the values in a field represent entries from an established set of codes. If this domain type is used, the authoritative reference that defines the values and their definitions needs to referenced (include a URL, publication citation, etc.).\n"
"\n"
"Examples: Zip codes, U.S. Census FIPS codes, established industry abbreviations/codes, etc."))

