# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EA.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1130, 807)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_ea = QtWidgets.QTabWidget(Form)
        self.tab_ea.setTabPosition(QtWidgets.QTabWidget.West)
        self.tab_ea.setObjectName("tab_ea")
        self.tab_instructions = QtWidgets.QWidget()
        self.tab_instructions.setObjectName("tab_instructions")
        self.label_5 = QtWidgets.QLabel(self.tab_instructions)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 621, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(15, 0))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.RichText)
        self.label_5.setScaledContents(False)
        self.label_5.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_5.setIndent(0)
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(self.tab_instructions)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 661, 81))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_instructions)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 821, 31))
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_instructions)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 321, 16))
        self.label_4.setObjectName("label_4")
        self.tab_ea.addTab(self.tab_instructions, "")
        self.fgdc_detailed = QtWidgets.QWidget()
        self.fgdc_detailed.setObjectName("fgdc_detailed")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fgdc_detailed)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.detailed_frame = QtWidgets.QFrame(self.fgdc_detailed)
        self.detailed_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailed_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.detailed_frame.setObjectName("detailed_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.detailed_frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2.addWidget(self.detailed_frame)
        self.tab_ea.addTab(self.fgdc_detailed, "")
        self.fgdc_overview = QtWidgets.QWidget()
        self.fgdc_overview.setObjectName("fgdc_overview")
        self.label = QtWidgets.QLabel(self.fgdc_overview)
        self.label.setGeometry(QtCore.QRect(30, 30, 111, 16))
        self.label.setObjectName("label")
        self.fgdc_eaover = QtWidgets.QTextBrowser(self.fgdc_overview)
        self.fgdc_eaover.setGeometry(QtCore.QRect(30, 50, 571, 192))
        self.fgdc_eaover.setReadOnly(False)
        self.fgdc_eaover.setPlaceholderText("")
        self.fgdc_eaover.setObjectName("fgdc_eaover")
        self.label_6 = QtWidgets.QLabel(self.fgdc_overview)
        self.label_6.setGeometry(QtCore.QRect(30, 250, 111, 16))
        self.label_6.setObjectName("label_6")
        self.fgdc_eadetcit = QtWidgets.QTextBrowser(self.fgdc_overview)
        self.fgdc_eadetcit.setGeometry(QtCore.QRect(30, 270, 571, 192))
        self.fgdc_eadetcit.setReadOnly(False)
        self.fgdc_eadetcit.setPlaceholderText("")
        self.fgdc_eadetcit.setObjectName("fgdc_eadetcit")
        self.tab_ea.addTab(self.fgdc_overview, "")
        self.verticalLayout.addWidget(self.tab_ea)

        self.retranslateUi(Form)
        self.tab_ea.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setToolTip(_translate("Form", "Required"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic; color:#55aaff;\">Provide Specific Information about the data content, organization, units, and values.</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "If this record describes a CSV, Shapefile, or other tabular or spatial dataset you must fill the Detailed section. Use the \'import from dataset\' functionality on the menubar to autopopulate this section with the column labels and values. Then provide definitions for each column (attribute) and values. "))
        self.label_3.setText(_translate("Form", "If this record describes a CSV, Shapefile, or other tabular or spatial dataset you must fill the Detailed section. Use the \'import from dataset\' functionality on the menubar to autopopulate this section with the column labels and values. Then provide definitions for each column (attribute) and values. "))
        self.label_4.setText(_translate("Form", "Use both if that more provides more clarity to data users."))
        self.tab_ea.setTabText(self.tab_ea.indexOf(self.tab_instructions), _translate("Form", "Instructions"))
        self.tab_ea.setTabText(self.tab_ea.indexOf(self.fgdc_detailed), _translate("Form", "Detailed"))
        self.label.setText(_translate("Form", "Overview Description"))
        self.label_6.setText(_translate("Form", "Citation"))
        self.tab_ea.setTabText(self.tab_ea.indexOf(self.fgdc_overview), _translate("Form", "Overview"))

