# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MetadataDate.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(594, 302)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fgdc_timeperd = QtWidgets.QGroupBox(Form)
        self.fgdc_timeperd.setObjectName("fgdc_timeperd")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.fgdc_timeperd)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.fgdc_timeperd)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.groupBox_2 = QtWidgets.QGroupBox(self.fgdc_timeperd)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox.setTitle("")
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(20, 10, 82, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(130, 10, 82, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(230, 10, 101, 17))
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.fgdc_timeinfo = QtWidgets.QStackedWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.fgdc_timeinfo.setFont(font)
        self.fgdc_timeinfo.setObjectName("fgdc_timeinfo")
        self.timeinfoPage1 = QtWidgets.QWidget()
        self.timeinfoPage1.setObjectName("timeinfoPage1")
        self.label_4 = QtWidgets.QLabel(self.timeinfoPage1)
        self.label_4.setGeometry(QtCore.QRect(120, 10, 101, 16))
        self.label_4.setObjectName("label_4")
        self.dateEdit = QtWidgets.QLineEdit(self.timeinfoPage1)
        self.dateEdit.setGeometry(QtCore.QRect(120, 30, 113, 20))
        self.dateEdit.setMaxLength(8)
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit0 = QtWidgets.QDateEdit(self.timeinfoPage1)
        self.dateEdit0.setGeometry(QtCore.QRect(230, 30, 16, 21))
        self.dateEdit0.setCalendarPopup(True)
        self.dateEdit0.setObjectName("dateEdit0")
        self.fgdc_timeinfo.addWidget(self.timeinfoPage1)
        self.timeinfoPage2 = QtWidgets.QWidget()
        self.timeinfoPage2.setObjectName("timeinfoPage2")
        self.label_5 = QtWidgets.QLabel(self.timeinfoPage2)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 161, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.timeinfoPage2)
        self.label_6.setGeometry(QtCore.QRect(190, 20, 131, 20))
        self.label_6.setObjectName("label_6")
        self.dateEdit_2 = QtWidgets.QLineEdit(self.timeinfoPage2)
        self.dateEdit_2.setGeometry(QtCore.QRect(30, 40, 113, 20))
        self.dateEdit_2.setMaxLength(8)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.dateEdit_3 = QtWidgets.QLineEdit(self.timeinfoPage2)
        self.dateEdit_3.setGeometry(QtCore.QRect(200, 40, 113, 20))
        self.dateEdit_3.setMaxLength(8)
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.fgdc_timeinfo.addWidget(self.timeinfoPage2)
        self.timeinfoPage3 = QtWidgets.QWidget()
        self.timeinfoPage3.setObjectName("timeinfoPage3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.timeinfoPage3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(self.timeinfoPage3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.SA_multi_dates = QtWidgets.QScrollArea(self.timeinfoPage3)
        self.SA_multi_dates.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.SA_multi_dates.setWidgetResizable(True)
        self.SA_multi_dates.setObjectName("SA_multi_dates")
        self.sa_multi_dates_content = QtWidgets.QWidget()
        self.sa_multi_dates_content.setGeometry(QtCore.QRect(0, 0, 447, 86))
        self.sa_multi_dates_content.setObjectName("sa_multi_dates_content")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.sa_multi_dates_content)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.SA_multi_dates.setWidget(self.sa_multi_dates_content)
        self.verticalLayout.addWidget(self.SA_multi_dates)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.timeinfoPage3)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.timeinfoPage3)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.fgdc_timeinfo.addWidget(self.timeinfoPage3)
        self.verticalLayout_2.addWidget(self.fgdc_timeinfo)
        self.fgdc_timeinfo.raise_()
        self.groupBox.raise_()
        self.horizontalLayout_5.addWidget(self.groupBox_2)
        self.label_3 = QtWidgets.QLabel(self.fgdc_timeperd)
        self.label_3.setMaximumSize(QtCore.QSize(85, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setItalic(True)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_8 = QtWidgets.QLabel(self.fgdc_timeperd)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_4.addWidget(self.label_8)
        self.fgdc_current = QtWidgets.QComboBox(self.fgdc_timeperd)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_current.sizePolicy().hasHeightForWidth())
        self.fgdc_current.setSizePolicy(sizePolicy)
        self.fgdc_current.setMinimumSize(QtCore.QSize(200, 0))
        self.fgdc_current.setEditable(True)
        self.fgdc_current.setObjectName("fgdc_current")
        self.fgdc_current.addItem("")
        self.fgdc_current.setItemText(0, "")
        self.fgdc_current.addItem("")
        self.fgdc_current.addItem("")
        self.fgdc_current.addItem("")
        self.fgdc_current.addItem("")
        self.horizontalLayout_4.addWidget(self.fgdc_current)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.fgdc_timeperd)

        self.retranslateUi(Form)
        self.fgdc_timeinfo.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_timeperd.setTitle(_translate("Form", "Time Period Information"))
        self.label_2.setText(_translate("Form", "What is the time period of the information represented in the data set?"))
        self.groupBox_2.setTitle(_translate("Form", "GroupBox"))
        self.radioButton.setText(_translate("Form", "Single Date"))
        self.radioButton_2.setText(_translate("Form", "Date Range"))
        self.radioButton_3.setText(_translate("Form", "Multiple Dates"))
        self.label_4.setText(_translate("Form", "Date (YYYYMMDD)"))
        self.dateEdit0.setDisplayFormat(_translate("Form", "yyyy/MM/dd"))
        self.label_5.setText(_translate("Form", "BeginningDate (YYYYMMDD)"))
        self.label_6.setText(_translate("Form", "End Date (YYYYMMDD)"))
        self.label_7.setText(_translate("Form", "Add Series of Dates (YYYYMMDD)"))
        self.pushButton.setText(_translate("Form", "Add Another Date"))
        self.pushButton_2.setText(_translate("Form", "Delete Selected"))
        self.label_3.setText(_translate("Form", "Enter information for only one option, either \'Single Date\', \'Date Range\', or \'Multiple Dates\'."))
        self.label_8.setText(_translate("Form", "Currentness Reference"))
        self.fgdc_current.setItemText(1, _translate("Form", "ground condition"))
        self.fgdc_current.setItemText(2, _translate("Form", "observed"))
        self.fgdc_current.setItemText(3, _translate("Form", "publication date"))
        self.fgdc_current.setItemText(4, _translate("Form", "See Supplemental Info"))

