# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PointOfContact.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_USGSContactInfoWidgetMain(object):
    def setupUi(self, USGSContactInfoWidgetMain):
        USGSContactInfoWidgetMain.setObjectName("USGSContactInfoWidgetMain")
        USGSContactInfoWidgetMain.resize(530, 90)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(USGSContactInfoWidgetMain.sizePolicy().hasHeightForWidth())
        USGSContactInfoWidgetMain.setSizePolicy(sizePolicy)
        USGSContactInfoWidgetMain.setMaximumSize(QtCore.QSize(16777215, 16777215))
        USGSContactInfoWidgetMain.setAcceptDrops(True)
        USGSContactInfoWidgetMain.setStyleSheet("font: 9pt \"Arial\";\n"
"color: rgb(60, 60, 60);")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(USGSContactInfoWidgetMain)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(USGSContactInfoWidgetMain)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setStyleSheet("font: bold;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.rbtn_yes = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_yes.setAutoFillBackground(True)
        self.rbtn_yes.setChecked(True)
        self.rbtn_yes.setObjectName("rbtn_yes")
        self.horizontalLayout.addWidget(self.rbtn_yes)
        self.rbtn_no = QtWidgets.QRadioButton(self.groupBox)
        self.rbtn_no.setAutoFillBackground(True)
        self.rbtn_no.setChecked(False)
        self.rbtn_no.setObjectName("rbtn_no")
        self.horizontalLayout.addWidget(self.rbtn_no)
        self.main_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setStyleSheet("font: italic;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.main_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(0, 20))
        self.label_2.setStyleSheet("font: italic;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.main_layout.addLayout(self.horizontalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.main_layout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.main_layout)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(USGSContactInfoWidgetMain)
        QtCore.QMetaObject.connectSlotsByName(USGSContactInfoWidgetMain)

    def retranslateUi(self, USGSContactInfoWidgetMain):
        _translate = QtCore.QCoreApplication.translate
        USGSContactInfoWidgetMain.setWindowTitle(_translate("USGSContactInfoWidgetMain", "Form"))
        self.label.setText(_translate("USGSContactInfoWidgetMain", "Is there a contact person or agency for this dataset?"))
        self.rbtn_yes.setText(_translate("USGSContactInfoWidgetMain", "Yes"))
        self.rbtn_no.setText(_translate("USGSContactInfoWidgetMain", "No"))
        self.label_3.setText(_translate("USGSContactInfoWidgetMain", "Having a data set contact is very helpful."))
        self.label_2.setText(_translate("USGSContactInfoWidgetMain", "This is someone who could be contacted for questions about the dataset."))

