# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'repeating_element.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(476, 393)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.button_frame = QtWidgets.QFrame(Form)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.button_frame)
        self.horizontalLayout.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.italic_label = QtWidgets.QLabel(self.button_frame)
        self.italic_label.setStyleSheet("font: italic;")
        self.italic_label.setText("")
        self.italic_label.setObjectName("italic_label")
        self.horizontalLayout.addWidget(self.italic_label)
        spacerItem = QtWidgets.QSpacerItem(315, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.addAnother = QtWidgets.QPushButton(self.button_frame)
        self.addAnother.setObjectName("addAnother")
        self.horizontalLayout.addWidget(self.addAnother)
        self.popOff = QtWidgets.QPushButton(self.button_frame)
        self.popOff.setObjectName("popOff")
        self.horizontalLayout.addWidget(self.popOff)
        self.verticalLayout.addWidget(self.button_frame)
        self.vertical_scroll = QtWidgets.QScrollArea(Form)
        self.vertical_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.vertical_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vertical_scroll.setWidgetResizable(True)
        self.vertical_scroll.setObjectName("vertical_scroll")
        self.vertical_contents = QtWidgets.QWidget()
        self.vertical_contents.setGeometry(QtCore.QRect(0, 0, 474, 121))
        self.vertical_contents.setObjectName("vertical_contents")
        self.vertical_layout_2 = QtWidgets.QVBoxLayout(self.vertical_contents)
        self.vertical_layout_2.setContentsMargins(3, 3, 3, 3)
        self.vertical_layout_2.setSpacing(3)
        self.vertical_layout_2.setObjectName("vertical_layout_2")
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vertical_layout_2.addItem(spacerItem1)
        self.vertical_scroll.setWidget(self.vertical_contents)
        self.verticalLayout.addWidget(self.vertical_scroll)
        self.horizontal_scroll = QtWidgets.QScrollArea(Form)
        self.horizontal_scroll.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.horizontal_scroll.setFrameShadow(QtWidgets.QFrame.Plain)
        self.horizontal_scroll.setWidgetResizable(True)
        self.horizontal_scroll.setObjectName("horizontal_scroll")
        self.horizontal_contents = QtWidgets.QWidget()
        self.horizontal_contents.setGeometry(QtCore.QRect(0, 0, 474, 120))
        self.horizontal_contents.setObjectName("horizontal_contents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontal_contents)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontal_scroll.setWidget(self.horizontal_contents)
        self.verticalLayout.addWidget(self.horizontal_scroll)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.frame)
        self.tab_widget = QtWidgets.QTabWidget(Form)
        self.tab_widget.setStyleSheet("")
        self.tab_widget.setElideMode(QtCore.Qt.ElideNone)
        self.tab_widget.setObjectName("tab_widget")
        self.verticalLayout.addWidget(self.tab_widget)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        self.tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addAnother.setText(_translate("Form", "PushButton"))
        self.popOff.setText(_translate("Form", "PushButton"))

