# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SRCInfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(824, 423)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fgdc_srcinfo = QtWidgets.QGroupBox(Form)
        self.fgdc_srcinfo.setObjectName("fgdc_srcinfo")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fgdc_srcinfo)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_citation = QtWidgets.QFrame(self.fgdc_srcinfo)
        self.frame_citation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_citation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_citation.setLineWidth(0)
        self.frame_citation.setObjectName("frame_citation")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_citation)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_4.addWidget(self.frame_citation)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_timeperd = QtWidgets.QFrame(self.fgdc_srcinfo)
        self.frame_timeperd.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_timeperd.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_timeperd.setLineWidth(0)
        self.frame_timeperd.setObjectName("frame_timeperd")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_timeperd)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3.addWidget(self.frame_timeperd)
        self.groupBox = QtWidgets.QGroupBox(self.fgdc_srcinfo)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.fgdc_srccitea = QtWidgets.QLineEdit(self.groupBox)
        self.fgdc_srccitea.setObjectName("fgdc_srccitea")
        self.verticalLayout_12.addWidget(self.fgdc_srccitea)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_14.addItem(spacerItem2)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem3)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.fgdc_srcscale = QtWidgets.QLineEdit(self.groupBox)
        self.fgdc_srcscale.setObjectName("fgdc_srcscale")
        self.verticalLayout_16.addWidget(self.fgdc_srcscale)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.fgdc_srccontr = QtWidgets.QLineEdit(self.groupBox)
        self.fgdc_srccontr.setObjectName("fgdc_srccontr")
        self.verticalLayout_15.addWidget(self.fgdc_srccontr)
        self.horizontalLayout.addLayout(self.verticalLayout_15)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.fgdc_typesrc = QtWidgets.QComboBox(self.groupBox)
        self.fgdc_typesrc.setEditable(True)
        self.fgdc_typesrc.setObjectName("fgdc_typesrc")
        self.fgdc_typesrc.addItem("")
        self.verticalLayout_13.addWidget(self.fgdc_typesrc)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7.addWidget(self.fgdc_srcinfo)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_srcinfo.setTitle(_translate("Form", "Source Input"))
        self.label_7.setText(_translate("Form", "Abbreviation / Short Name for the Input Data   (Updated as Needed)"))
        self.label_10.setText(_translate("Form", "1:"))
        self.label_9.setText(_translate("Form", "Source Scale"))
        self.fgdc_srcscale.setPlaceholderText(_translate("Form", "24000"))
        self.label_8.setText(_translate("Form", "Contribution of Source Input   (Update as Needed)"))
        self.label_12.setText(_translate("Form", "Type of Resource"))
        self.fgdc_typesrc.setItemText(0, _translate("Form", "Digital and/or Hardcopy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

