# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spref.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_fgdc_spref(object):
    def setupUi(self, fgdc_spref):
        fgdc_spref.setObjectName("fgdc_spref")
        fgdc_spref.resize(487, 553)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(fgdc_spref)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fgdc_horizsys = QtWidgets.QGroupBox(fgdc_spref)
        self.fgdc_horizsys.setTitle("")
        self.fgdc_horizsys.setObjectName("fgdc_horizsys")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fgdc_horizsys)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.fgdc_horizsys)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setStyleSheet("font: bold;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rbtn_yes = QtWidgets.QRadioButton(self.fgdc_horizsys)
        self.rbtn_yes.setAutoFillBackground(True)
        self.rbtn_yes.setChecked(True)
        self.rbtn_yes.setObjectName("rbtn_yes")
        self.horizontalLayout_3.addWidget(self.rbtn_yes)
        self.rbtn_no = QtWidgets.QRadioButton(self.fgdc_horizsys)
        self.rbtn_no.setAutoFillBackground(True)
        self.rbtn_no.setChecked(False)
        self.rbtn_no.setObjectName("rbtn_no")
        self.horizontalLayout_3.addWidget(self.rbtn_no)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horiz_layout = QtWidgets.QGroupBox(self.fgdc_horizsys)
        self.horiz_layout.setStyleSheet("")
        self.horiz_layout.setObjectName("horiz_layout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horiz_layout)
        self.verticalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame = QtWidgets.QFrame(self.horiz_layout)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_geographic = QtWidgets.QRadioButton(self.frame)
        self.btn_geographic.setChecked(True)
        self.btn_geographic.setObjectName("btn_geographic")
        self.horizontalLayout.addWidget(self.btn_geographic)
        self.btn_planar = QtWidgets.QRadioButton(self.frame)
        self.btn_planar.setObjectName("btn_planar")
        self.horizontalLayout.addWidget(self.btn_planar)
        self.btn_local = QtWidgets.QRadioButton(self.frame)
        self.btn_local.setObjectName("btn_local")
        self.horizontalLayout.addWidget(self.btn_local)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stack_definition = QtWidgets.QStackedWidget(self.frame)
        self.stack_definition.setObjectName("stack_definition")
        self.fgdc_geograph = QtWidgets.QWidget()
        self.fgdc_geograph.setObjectName("fgdc_geograph")
        self.formLayout = QtWidgets.QFormLayout(self.fgdc_geograph)
        self.formLayout.setContentsMargins(10, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.fgdc_geograph)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fgdc_latres = QtWidgets.QLineEdit(self.fgdc_geograph)
        self.fgdc_latres.setObjectName("fgdc_latres")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_latres)
        self.label_2 = QtWidgets.QLabel(self.fgdc_geograph)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fgdc_longres = QtWidgets.QLineEdit(self.fgdc_geograph)
        self.fgdc_longres.setObjectName("fgdc_longres")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgdc_longres)
        self.label_3 = QtWidgets.QLabel(self.fgdc_geograph)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fgdc_geogunit = QtWidgets.QComboBox(self.fgdc_geograph)
        self.fgdc_geogunit.setEditable(True)
        self.fgdc_geogunit.setObjectName("fgdc_geogunit")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.fgdc_geogunit.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgdc_geogunit)
        self.stack_definition.addWidget(self.fgdc_geograph)
        self.fgdc_planar = QtWidgets.QWidget()
        self.fgdc_planar.setObjectName("fgdc_planar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fgdc_planar)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_projection = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_projection.setChecked(True)
        self.btn_projection.setObjectName("btn_projection")
        self.btngrp_planar = QtWidgets.QButtonGroup(fgdc_spref)
        self.btngrp_planar.setObjectName("btngrp_planar")
        self.btngrp_planar.addButton(self.btn_projection)
        self.horizontalLayout_2.addWidget(self.btn_projection)
        self.btn_grid = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_grid.setObjectName("btn_grid")
        self.btngrp_planar.addButton(self.btn_grid)
        self.horizontalLayout_2.addWidget(self.btn_grid)
        self.btn_localp = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_localp.setObjectName("btn_localp")
        self.btngrp_planar.addButton(self.btn_localp)
        self.horizontalLayout_2.addWidget(self.btn_localp)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.stack_planar = QtWidgets.QStackedWidget(self.fgdc_planar)
        self.stack_planar.setObjectName("stack_planar")
        self.fgdc_mapproj = QtWidgets.QWidget()
        self.fgdc_mapproj.setObjectName("fgdc_mapproj")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.fgdc_mapproj)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.fgdc_mapproj)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.fgdc_mapprojn = QtWidgets.QComboBox(self.fgdc_mapproj)
        self.fgdc_mapprojn.setEditable(True)
        self.fgdc_mapprojn.setObjectName("fgdc_mapprojn")
        self.horizontalLayout_4.addWidget(self.fgdc_mapprojn)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.stack_planar.addWidget(self.fgdc_mapproj)
        self.fgdc_gridsys = QtWidgets.QWidget()
        self.fgdc_gridsys.setObjectName("fgdc_gridsys")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fgdc_gridsys)
        self.verticalLayout_8.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget = QtWidgets.QWidget(self.fgdc_gridsys)
        self.widget.setObjectName("widget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.fgdc_gridsysn = QtWidgets.QComboBox(self.widget)
        self.fgdc_gridsysn.setObjectName("fgdc_gridsysn")
        self.horizontalLayout_5.addWidget(self.fgdc_gridsysn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.gridsys_contents = QtWidgets.QWidget(self.widget)
        self.gridsys_contents.setObjectName("gridsys_contents")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gridsys_contents)
        self.formLayout_2.setContentsMargins(0, 0, 0, 3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.gridsys_contents)
        spacerItem4 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem4)
        self.verticalLayout_8.addWidget(self.widget)
        self.stack_planar.addWidget(self.fgdc_gridsys)
        self.fgdc_local = QtWidgets.QWidget()
        self.fgdc_local.setObjectName("fgdc_local")
        self.formLayout_3 = QtWidgets.QFormLayout(self.fgdc_local)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.fgdc_local)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fgdc_localpd = QtWidgets.QLineEdit(self.fgdc_local)
        self.fgdc_localpd.setObjectName("fgdc_localpd")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_localpd)
        self.label_6 = QtWidgets.QLabel(self.fgdc_local)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fgdc_localpgi = QtWidgets.QLineEdit(self.fgdc_local)
        self.fgdc_localpgi.setObjectName("fgdc_localpgi")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_localpgi)
        self.stack_planar.addWidget(self.fgdc_local)
        self.verticalLayout_3.addWidget(self.stack_planar)
        self.groupBox = QtWidgets.QGroupBox(self.fgdc_planar)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_8.setContentsMargins(3, 3, 3, 3)
        self.formLayout_8.setObjectName("formLayout_8")
        self.help_plance = QtWidgets.QLabel(self.groupBox)
        self.help_plance.setObjectName("help_plance")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.help_plance)
        self.fgdc_plance = QtWidgets.QComboBox(self.groupBox)
        self.fgdc_plance.setObjectName("fgdc_plance")
        self.fgdc_plance.addItem("")
        self.fgdc_plance.addItem("")
        self.fgdc_plance.addItem("")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_plance)
        self.help_absres = QtWidgets.QLabel(self.groupBox)
        self.help_absres.setObjectName("help_absres")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.help_absres)
        self.fgdc_absres = QtWidgets.QLineEdit(self.groupBox)
        self.fgdc_absres.setObjectName("fgdc_absres")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgdc_absres)
        self.help_ordres = QtWidgets.QLabel(self.groupBox)
        self.help_ordres.setObjectName("help_ordres")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.help_ordres)
        self.fgdc_ordres = QtWidgets.QLineEdit(self.groupBox)
        self.fgdc_ordres.setObjectName("fgdc_ordres")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgdc_ordres)
        self.help_plandu = QtWidgets.QLabel(self.groupBox)
        self.help_plandu.setObjectName("help_plandu")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.help_plandu)
        self.fgdc_plandu = QtWidgets.QComboBox(self.groupBox)
        self.fgdc_plandu.setObjectName("fgdc_plandu")
        self.fgdc_plandu.addItem("")
        self.fgdc_plandu.addItem("")
        self.fgdc_plandu.addItem("")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fgdc_plandu)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.stack_definition.addWidget(self.fgdc_planar)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayout_7 = QtWidgets.QFormLayout(self.page)
        self.formLayout_7.setContentsMargins(0, 0, 0, 0)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setObjectName("label_12")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.fgdc_localdes = QtWidgets.QLineEdit(self.page)
        self.fgdc_localdes.setObjectName("fgdc_localdes")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_localdes)
        self.label_14 = QtWidgets.QLabel(self.page)
        self.label_14.setObjectName("label_14")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.fgdc_localgeo = QtWidgets.QLineEdit(self.page)
        self.fgdc_localgeo.setObjectName("fgdc_localgeo")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_localgeo)
        self.stack_definition.addWidget(self.page)
        self.verticalLayout.addWidget(self.stack_definition)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_5.addWidget(self.frame)
        self.fgdc_geodetic = QtWidgets.QGroupBox(self.horiz_layout)
        self.fgdc_geodetic.setObjectName("fgdc_geodetic")
        self.formLayout_5 = QtWidgets.QFormLayout(self.fgdc_geodetic)
        self.formLayout_5.setContentsMargins(3, 3, 3, 3)
        self.formLayout_5.setHorizontalSpacing(3)
        self.formLayout_5.setVerticalSpacing(6)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_8 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fgdc_ellips = QtWidgets.QComboBox(self.fgdc_geodetic)
        self.fgdc_ellips.setEditable(True)
        self.fgdc_ellips.setObjectName("fgdc_ellips")
        self.fgdc_ellips.addItem("")
        self.fgdc_ellips.addItem("")
        self.fgdc_ellips.addItem("")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_ellips)
        self.label_9 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fgdc_semiaxis = QtWidgets.QLineEdit(self.fgdc_geodetic)
        self.fgdc_semiaxis.setObjectName("fgdc_semiaxis")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgdc_semiaxis)
        self.label_11 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.fgdc_denflat = QtWidgets.QLineEdit(self.fgdc_geodetic)
        self.fgdc_denflat.setObjectName("fgdc_denflat")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgdc_denflat)
        self.fgdc_horizdn = QtWidgets.QComboBox(self.fgdc_geodetic)
        self.fgdc_horizdn.setEditable(True)
        self.fgdc_horizdn.setObjectName("fgdc_horizdn")
        self.fgdc_horizdn.addItem("")
        self.fgdc_horizdn.addItem("")
        self.fgdc_horizdn.addItem("")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_horizdn)
        self.verticalLayout_5.addWidget(self.fgdc_geodetic)
        self.verticalLayout_4.addWidget(self.horiz_layout)
        self.verticalLayout_6.addWidget(self.fgdc_horizsys)

        self.retranslateUi(fgdc_spref)
        self.stack_definition.setCurrentIndex(1)
        self.fgdc_geogunit.setCurrentIndex(0)
        self.stack_planar.setCurrentIndex(1)
        self.fgdc_ellips.setCurrentIndex(2)
        self.fgdc_horizdn.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(fgdc_spref)

    def retranslateUi(self, fgdc_spref):
        _translate = QtCore.QCoreApplication.translate
        fgdc_spref.setWindowTitle(_translate("fgdc_spref", "Form"))
        self.label_13.setText(_translate("fgdc_spref", "Is there a datum or projection used in this Dataset? "))
        self.rbtn_yes.setText(_translate("fgdc_spref", "Yes"))
        self.rbtn_no.setText(_translate("fgdc_spref", "No"))
        self.horiz_layout.setTitle(_translate("fgdc_spref", "Horizontal Coordinate System"))
        self.btn_geographic.setText(_translate("fgdc_spref", "Geographic"))
        self.btn_planar.setText(_translate("fgdc_spref", "Planar"))
        self.btn_local.setText(_translate("fgdc_spref", "Local"))
        self.label.setText(_translate("fgdc_spref", "Latitude Resolution"))
        self.fgdc_latres.setText(_translate("fgdc_spref", "0.0001"))
        self.label_2.setText(_translate("fgdc_spref", "Longitude Resolution"))
        self.fgdc_longres.setText(_translate("fgdc_spref", "0.0001"))
        self.label_3.setText(_translate("fgdc_spref", "Geographic Coordinate Units"))
        self.fgdc_geogunit.setCurrentText(_translate("fgdc_spref", "Decimal degrees"))
        self.fgdc_geogunit.setItemText(0, _translate("fgdc_spref", "Decimal degrees"))
        self.fgdc_geogunit.setItemText(1, _translate("fgdc_spref", "Decimal minutes"))
        self.fgdc_geogunit.setItemText(2, _translate("fgdc_spref", "Decimal seconds"))
        self.fgdc_geogunit.setItemText(3, _translate("fgdc_spref", "Degrees and decimal minutes"))
        self.fgdc_geogunit.setItemText(4, _translate("fgdc_spref", "Degrees, minutes, and decimal seconds"))
        self.fgdc_geogunit.setItemText(5, _translate("fgdc_spref", "Radians"))
        self.fgdc_geogunit.setItemText(6, _translate("fgdc_spref", "Grads"))
        self.btn_projection.setText(_translate("fgdc_spref", "Map Projection"))
        self.btn_grid.setText(_translate("fgdc_spref", "Grid Coordinate System"))
        self.btn_localp.setText(_translate("fgdc_spref", "Local Planar"))
        self.label_4.setText(_translate("fgdc_spref", "Projection Name"))
        self.label_7.setText(_translate("fgdc_spref", "Grid System Name"))
        self.label_5.setText(_translate("fgdc_spref", "Local Planar Description"))
        self.label_6.setText(_translate("fgdc_spref", "Local Planar georeference information"))
        self.groupBox.setTitle(_translate("fgdc_spref", "Planar Coordinate Information"))
        self.help_plance.setText(_translate("fgdc_spref", "Planar Coordinate Encoding Method"))
        self.fgdc_plance.setItemText(0, _translate("fgdc_spref", "coordinate pair"))
        self.fgdc_plance.setItemText(1, _translate("fgdc_spref", "distance and bearing"))
        self.fgdc_plance.setItemText(2, _translate("fgdc_spref", "row and column"))
        self.help_absres.setText(_translate("fgdc_spref", "Abscissa Resolution"))
        self.fgdc_absres.setText(_translate("fgdc_spref", "0.0001"))
        self.help_ordres.setText(_translate("fgdc_spref", "Ordinate Resolution"))
        self.fgdc_ordres.setText(_translate("fgdc_spref", "0.0001"))
        self.help_plandu.setText(_translate("fgdc_spref", "Planar Units"))
        self.fgdc_plandu.setItemText(0, _translate("fgdc_spref", "meters"))
        self.fgdc_plandu.setItemText(1, _translate("fgdc_spref", "International feet"))
        self.fgdc_plandu.setItemText(2, _translate("fgdc_spref", "survey feet"))
        self.label_12.setText(_translate("fgdc_spref", "Local Description"))
        self.label_14.setText(_translate("fgdc_spref", "Local Georeference Information"))
        self.fgdc_geodetic.setTitle(_translate("fgdc_spref", "Datum (optional)"))
        self.label_8.setText(_translate("fgdc_spref", "Datum Name"))
        self.fgdc_ellips.setItemText(0, _translate("fgdc_spref", "Clarke 1866"))
        self.fgdc_ellips.setItemText(1, _translate("fgdc_spref", "Geodetic Reference System 1980"))
        self.fgdc_ellips.setItemText(2, _translate("fgdc_spref", "WGS_1984"))
        self.label_9.setText(_translate("fgdc_spref", "Elipsoid Name"))
        self.label_10.setText(_translate("fgdc_spref", "Semi-major Axis"))
        self.fgdc_semiaxis.setText(_translate("fgdc_spref", "6378137.000000"))
        self.label_11.setText(_translate("fgdc_spref", "Denominator Flattening Ratio"))
        self.fgdc_denflat.setText(_translate("fgdc_spref", "298.257224"))
        self.fgdc_horizdn.setItemText(0, _translate("fgdc_spref", "North American Datum of 1927 (NAD 27)"))
        self.fgdc_horizdn.setItemText(1, _translate("fgdc_spref", "North American Datum of 1983 (NAD 83)"))
        self.fgdc_horizdn.setItemText(2, _translate("fgdc_spref", "World Geodetic System 1984 (WGS 84)"))

