# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spref.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(496, 433)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontal_group_box = QtWidgets.QGroupBox(Form)
        self.horizontal_group_box.setTitle("")
        self.horizontal_group_box.setObjectName("horizontal_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.horizontal_group_box)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_13 = QtWidgets.QLabel(self.horizontal_group_box)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setStyleSheet("font: bold;")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_3.addWidget(self.label_13)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.rbtn_yes = QtWidgets.QRadioButton(self.horizontal_group_box)
        self.rbtn_yes.setAutoFillBackground(True)
        self.rbtn_yes.setChecked(True)
        self.rbtn_yes.setObjectName("rbtn_yes")
        self.horizontalLayout_3.addWidget(self.rbtn_yes)
        self.rbtn_no = QtWidgets.QRadioButton(self.horizontal_group_box)
        self.rbtn_no.setAutoFillBackground(True)
        self.rbtn_no.setChecked(False)
        self.rbtn_no.setObjectName("rbtn_no")
        self.horizontalLayout_3.addWidget(self.rbtn_no)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horiz_layout = QtWidgets.QGroupBox(self.horizontal_group_box)
        self.horiz_layout.setStyleSheet("")
        self.horiz_layout.setObjectName("horiz_layout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.horiz_layout)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fgdc_horizsys = QtWidgets.QFrame(self.horiz_layout)
        self.fgdc_horizsys.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fgdc_horizsys.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fgdc_horizsys.setObjectName("fgdc_horizsys")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fgdc_horizsys)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_geographic = QtWidgets.QRadioButton(self.fgdc_horizsys)
        self.btn_geographic.setChecked(True)
        self.btn_geographic.setObjectName("btn_geographic")
        self.horizontalLayout.addWidget(self.btn_geographic)
        self.btn_planar = QtWidgets.QRadioButton(self.fgdc_horizsys)
        self.btn_planar.setObjectName("btn_planar")
        self.horizontalLayout.addWidget(self.btn_planar)
        spacerItem1 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stack_definition = QtWidgets.QStackedWidget(self.fgdc_horizsys)
        self.stack_definition.setObjectName("stack_definition")
        self.fgdc_geograph = QtWidgets.QWidget()
        self.fgdc_geograph.setObjectName("fgdc_geograph")
        self.formLayout = QtWidgets.QFormLayout(self.fgdc_geograph)
        self.formLayout.setContentsMargins(10, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.frame = QtWidgets.QFrame(self.fgdc_geograph)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frame)
        self.fgdc_latres = QtWidgets.QLineEdit(self.fgdc_geograph)
        self.fgdc_latres.setObjectName("fgdc_latres")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgdc_latres)
        self.label = QtWidgets.QLabel(self.fgdc_geograph)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.fgdc_geograph)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.fgdc_longres = QtWidgets.QLineEdit(self.fgdc_geograph)
        self.fgdc_longres.setObjectName("fgdc_longres")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgdc_longres)
        self.label_3 = QtWidgets.QLabel(self.fgdc_geograph)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.fgdc_geogunit = QtWidgets.QComboBox(self.fgdc_geograph)
        self.fgdc_geogunit.setEditable(True)
        self.fgdc_geogunit.setObjectName("fgdc_geogunit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.fgdc_geogunit)
        self.stack_definition.addWidget(self.fgdc_geograph)
        self.fgdc_planar = QtWidgets.QWidget()
        self.fgdc_planar.setObjectName("fgdc_planar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fgdc_planar)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(74, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_projection = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_projection.setChecked(True)
        self.btn_projection.setObjectName("btn_projection")
        self.btngrp_planar = QtWidgets.QButtonGroup(Form)
        self.btngrp_planar.setObjectName("btngrp_planar")
        self.btngrp_planar.addButton(self.btn_projection)
        self.horizontalLayout_2.addWidget(self.btn_projection)
        self.btn_grid = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_grid.setObjectName("btn_grid")
        self.btngrp_planar.addButton(self.btn_grid)
        self.horizontalLayout_2.addWidget(self.btn_grid)
        self.btn_local = QtWidgets.QRadioButton(self.fgdc_planar)
        self.btn_local.setObjectName("btn_local")
        self.btngrp_planar.addButton(self.btn_local)
        self.horizontalLayout_2.addWidget(self.btn_local)
        spacerItem3 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.stack_planar = QtWidgets.QStackedWidget(self.fgdc_planar)
        self.stack_planar.setObjectName("stack_planar")
        self.fgdc_mapproj = QtWidgets.QWidget()
        self.fgdc_mapproj.setObjectName("fgdc_mapproj")
        self.formLayout_2 = QtWidgets.QFormLayout(self.fgdc_mapproj)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.fgdc_mapproj)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.fgdc_mapprojn = QtWidgets.QComboBox(self.fgdc_mapproj)
        self.fgdc_mapprojn.setObjectName("fgdc_mapprojn")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_mapprojn)
        self.projection_params = QtWidgets.QScrollArea(self.fgdc_mapproj)
        self.projection_params.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projection_params.setWidgetResizable(True)
        self.projection_params.setObjectName("projection_params")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout_6 = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout_6.setContentsMargins(0, 0, 0, 0)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName("label_12")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.projection_params.setWidget(self.scrollAreaWidgetContents)
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.projection_params)
        self.stack_planar.addWidget(self.fgdc_mapproj)
        self.fgdc_gridsys = QtWidgets.QWidget()
        self.fgdc_gridsys.setObjectName("fgdc_gridsys")
        self.formLayout_4 = QtWidgets.QFormLayout(self.fgdc_gridsys)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtWidgets.QLabel(self.fgdc_gridsys)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.fgdc_gridsysn = QtWidgets.QComboBox(self.fgdc_gridsys)
        self.fgdc_gridsysn.setObjectName("fgdc_gridsysn")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_gridsysn)
        self.stack_planar.addWidget(self.fgdc_gridsys)
        self.fgdc_local = QtWidgets.QWidget()
        self.fgdc_local.setObjectName("fgdc_local")
        self.formLayout_3 = QtWidgets.QFormLayout(self.fgdc_local)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtWidgets.QLabel(self.fgdc_local)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.fgdc_localdes = QtWidgets.QLineEdit(self.fgdc_local)
        self.fgdc_localdes.setObjectName("fgdc_localdes")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_localdes)
        self.label_6 = QtWidgets.QLabel(self.fgdc_local)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.fgdc_localgeo = QtWidgets.QLineEdit(self.fgdc_local)
        self.fgdc_localgeo.setObjectName("fgdc_localgeo")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_localgeo)
        self.stack_planar.addWidget(self.fgdc_local)
        self.verticalLayout_3.addWidget(self.stack_planar)
        self.stack_definition.addWidget(self.fgdc_planar)
        self.verticalLayout.addWidget(self.stack_definition)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.fgdc_geodetic = QtWidgets.QGroupBox(self.fgdc_horizsys)
        self.fgdc_geodetic.setObjectName("fgdc_geodetic")
        self.formLayout_5 = QtWidgets.QFormLayout(self.fgdc_geodetic)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_8 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_8.setObjectName("label_8")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.fgdc_ellips = QtWidgets.QComboBox(self.fgdc_geodetic)
        self.fgdc_ellips.setEditable(True)
        self.fgdc_ellips.setObjectName("fgdc_ellips")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fgdc_ellips)
        self.label_9 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_9.setObjectName("label_9")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_10.setObjectName("label_10")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.fgdc_semiaxis = QtWidgets.QLineEdit(self.fgdc_geodetic)
        self.fgdc_semiaxis.setObjectName("fgdc_semiaxis")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fgdc_semiaxis)
        self.label_11 = QtWidgets.QLabel(self.fgdc_geodetic)
        self.label_11.setObjectName("label_11")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.fgdc_denflat = QtWidgets.QLineEdit(self.fgdc_geodetic)
        self.fgdc_denflat.setObjectName("fgdc_denflat")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fgdc_denflat)
        self.fgdc_horizdn = QtWidgets.QComboBox(self.fgdc_geodetic)
        self.fgdc_horizdn.setEditable(True)
        self.fgdc_horizdn.setObjectName("fgdc_horizdn")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.fgdc_horizdn)
        self.verticalLayout_2.addWidget(self.fgdc_geodetic)
        self.verticalLayout_5.addWidget(self.fgdc_horizsys)
        self.verticalLayout_4.addWidget(self.horiz_layout)
        self.verticalLayout_6.addWidget(self.horizontal_group_box)

        self.retranslateUi(Form)
        self.stack_definition.setCurrentIndex(0)
        self.stack_planar.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Is there a datum or projection used in this Dataset  "))
        self.rbtn_yes.setText(_translate("Form", "Yes"))
        self.rbtn_no.setText(_translate("Form", "No"))
        self.horiz_layout.setTitle(_translate("Form", "Horizontal Coordinate System"))
        self.btn_geographic.setText(_translate("Form", "Geographic"))
        self.btn_planar.setText(_translate("Form", "Planar"))
        self.label.setText(_translate("Form", "Latitude Resolution"))
        self.label_2.setText(_translate("Form", "Longitude Resolution"))
        self.label_3.setText(_translate("Form", "Geographic Coordinate Units"))
        self.fgdc_geogunit.setCurrentText(_translate("Form", "Decimal degrees"))
        self.btn_projection.setText(_translate("Form", "Map Projection"))
        self.btn_grid.setText(_translate("Form", "Grid Coordinate System"))
        self.btn_local.setText(_translate("Form", "Local Planar"))
        self.label_4.setText(_translate("Form", "Projection Name"))
        self.label_12.setText(_translate("Form", "TextLabel"))
        self.label_7.setText(_translate("Form", "Grid System Name"))
        self.label_5.setText(_translate("Form", "Local Planar Description"))
        self.label_6.setText(_translate("Form", "Local Planar georeference information"))
        self.fgdc_geodetic.setTitle(_translate("Form", "Datum (optional)"))
        self.label_8.setText(_translate("Form", "Datum Name"))
        self.label_9.setText(_translate("Form", "Elipsoid NameName"))
        self.label_10.setText(_translate("Form", "Elipsoid NameName"))
        self.label_11.setText(_translate("Form", "Elipsoid NameName"))

