# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SRCInfo.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 468)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.fgdc_srcinfo = QtWidgets.QGroupBox(Form)
        self.fgdc_srcinfo.setObjectName("fgdc_srcinfo")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.fgdc_srcinfo)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.fgdc_title = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_title.setObjectName("fgdc_title")
        self.verticalLayout_2.addWidget(self.fgdc_title)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.fgdc_origin = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_origin.setObjectName("fgdc_origin")
        self.verticalLayout_3.addWidget(self.fgdc_origin)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.fgdc_publish = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_publish.setObjectName("fgdc_publish")
        self.verticalLayout_4.addWidget(self.fgdc_publish)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.fgdc_pubplace = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_pubplace.setObjectName("fgdc_pubplace")
        self.verticalLayout_5.addWidget(self.fgdc_pubplace)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_19.addLayout(self.verticalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.fgdc_geoform = QtWidgets.QComboBox(self.fgdc_srcinfo)
        self.fgdc_geoform.setEditable(True)
        self.fgdc_geoform.setObjectName("fgdc_geoform")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.fgdc_geoform.addItem("")
        self.verticalLayout_8.addWidget(self.fgdc_geoform)
        self.verticalLayout_18.addLayout(self.verticalLayout_8)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_12 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_13.addWidget(self.label_12)
        self.fgdc_typesrc = QtWidgets.QComboBox(self.fgdc_srcinfo)
        self.fgdc_typesrc.setEditable(True)
        self.fgdc_typesrc.setObjectName("fgdc_typesrc")
        self.fgdc_typesrc.addItem("")
        self.verticalLayout_13.addWidget(self.fgdc_typesrc)
        self.verticalLayout_18.addLayout(self.verticalLayout_13)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_37 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_37.setObjectName("label_37")
        self.verticalLayout.addWidget(self.label_37)
        self.fgdc_pubdate = QtWidgets.QWidget(self.fgdc_srcinfo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_pubdate.sizePolicy().hasHeightForWidth())
        self.fgdc_pubdate.setSizePolicy(sizePolicy)
        self.fgdc_pubdate.setMinimumSize(QtCore.QSize(0, 0))
        self.fgdc_pubdate.setMaximumSize(QtCore.QSize(221, 100))
        self.fgdc_pubdate.setObjectName("fgdc_pubdate")
        self.verticalLayout.addWidget(self.fgdc_pubdate)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_18.addLayout(self.verticalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_18)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.fgdc_onlink = QtWidgets.QFrame(self.fgdc_srcinfo)
        self.fgdc_onlink.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fgdc_onlink.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fgdc_onlink.setObjectName("fgdc_onlink")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.fgdc_onlink)
        self.verticalLayout_6.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fg_dc_onlink = QtWidgets.QVBoxLayout()
        self.fg_dc_onlink.setObjectName("fg_dc_onlink")
        self.verticalLayout_6.addLayout(self.fg_dc_onlink)
        self.horizontalLayout_5.addWidget(self.fgdc_onlink)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_5)
        self.verticalLayout_19.addLayout(self.horizontalLayout_3)
        self.fgdc_srctime = QtWidgets.QGroupBox(self.fgdc_srcinfo)
        self.fgdc_srctime.setObjectName("fgdc_srctime")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fgdc_srctime)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_38 = QtWidgets.QLabel(self.fgdc_srctime)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_9.addWidget(self.label_38)
        self.fgdc_begdate = QtWidgets.QWidget(self.fgdc_srctime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_begdate.sizePolicy().hasHeightForWidth())
        self.fgdc_begdate.setSizePolicy(sizePolicy)
        self.fgdc_begdate.setMinimumSize(QtCore.QSize(0, 0))
        self.fgdc_begdate.setMaximumSize(QtCore.QSize(221, 100))
        self.fgdc_begdate.setObjectName("fgdc_begdate")
        self.verticalLayout_9.addWidget(self.fgdc_begdate)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_39 = QtWidgets.QLabel(self.fgdc_srctime)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_10.addWidget(self.label_39)
        self.fgdc_enddate = QtWidgets.QWidget(self.fgdc_srctime)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_enddate.sizePolicy().hasHeightForWidth())
        self.fgdc_enddate.setSizePolicy(sizePolicy)
        self.fgdc_enddate.setMinimumSize(QtCore.QSize(0, 0))
        self.fgdc_enddate.setMaximumSize(QtCore.QSize(221, 100))
        self.fgdc_enddate.setObjectName("fgdc_enddate")
        self.verticalLayout_10.addWidget(self.fgdc_enddate)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.fgdc_srctime)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.fgdc_srccurr = QtWidgets.QComboBox(self.fgdc_srctime)
        self.fgdc_srccurr.setEditable(True)
        self.fgdc_srccurr.setObjectName("fgdc_srccurr")
        self.fgdc_srccurr.addItem("")
        self.fgdc_srccurr.addItem("")
        self.fgdc_srccurr.addItem("")
        self.verticalLayout_11.addWidget(self.fgdc_srccurr)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_19.addWidget(self.fgdc_srctime)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_12.addWidget(self.label_7)
        self.fgdc_srccitea = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_srccitea.setObjectName("fgdc_srccitea")
        self.verticalLayout_12.addWidget(self.fgdc_srccitea)
        self.horizontalLayout_8.addLayout(self.verticalLayout_12)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_11 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_14.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_14.addWidget(self.label_10)
        self.horizontalLayout_8.addLayout(self.verticalLayout_14)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_9 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_16.addWidget(self.label_9)
        self.fgdc_srcscale = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_srcscale.setObjectName("fgdc_srcscale")
        self.verticalLayout_16.addWidget(self.fgdc_srcscale)
        self.horizontalLayout_8.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_8)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.fgdc_srcinfo)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.fgdc_srccontr = QtWidgets.QLineEdit(self.fgdc_srcinfo)
        self.fgdc_srccontr.setObjectName("fgdc_srccontr")
        self.verticalLayout_15.addWidget(self.fgdc_srccontr)
        self.verticalLayout_17.addLayout(self.verticalLayout_15)
        self.verticalLayout_19.addLayout(self.verticalLayout_17)
        self.horizontalLayout_9.addLayout(self.verticalLayout_19)
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_37.raise_()
        self.label_6.raise_()
        self.fgdc_title.raise_()
        self.fgdc_origin.raise_()
        self.fgdc_publish.raise_()
        self.fgdc_pubplace.raise_()
        self.fgdc_geoform.raise_()
        self.label_5.raise_()
        self.fgdc_srccurr.raise_()
        self.fgdc_srctime.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.fgdc_srccitea.raise_()
        self.fgdc_srccontr.raise_()
        self.fgdc_srcscale.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.fgdc_onlink.raise_()
        self.label_12.raise_()
        self.fgdc_typesrc.raise_()
        self.horizontalLayout_7.addWidget(self.fgdc_srcinfo)

        self.retranslateUi(Form)
        self.fgdc_geoform.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_srcinfo.setTitle(_translate("Form", "Source Input"))
        self.label.setText(_translate("Form", "Title of Source Input"))
        self.label_2.setText(_translate("Form", "Author / Originator of Source Input"))
        self.label_4.setText(_translate("Form", "Publisher / Data Provider"))
        self.label_3.setText(_translate("Form", "Publication Place"))
        self.label_6.setText(_translate("Form", "Type of Data"))
        self.fgdc_geoform.setItemText(0, _translate("Form", "Vector Digital Data Set"))
        self.fgdc_geoform.setItemText(1, _translate("Form", "Raster Digital Data Set"))
        self.fgdc_geoform.setItemText(2, _translate("Form", "Raster Digital Data (Aerial Imagery)"))
        self.fgdc_geoform.setItemText(3, _translate("Form", "Publication (Book)"))
        self.fgdc_geoform.setItemText(4, _translate("Form", "Publication (Journal Article)"))
        self.fgdc_geoform.setItemText(5, _translate("Form", "Publication (Conference Proceeding)"))
        self.fgdc_geoform.setItemText(6, _translate("Form", "Paper Map"))
        self.fgdc_geoform.setItemText(7, _translate("Form", "Observed/Measured First-Hand"))
        self.fgdc_geoform.setItemText(8, _translate("Form", "Photographic Print"))
        self.fgdc_geoform.setItemText(9, _translate("Form", "Computer Program"))
        self.fgdc_geoform.setItemText(10, _translate("Form", "Other"))
        self.label_12.setText(_translate("Form", "Type of Resource"))
        self.fgdc_typesrc.setItemText(0, _translate("Form", "Digital and/or Hardcopy"))
        self.label_37.setText(_translate("Form", "Publication Date (YYYYMMDD)"))
        self.fgdc_srctime.setTitle(_translate("Form", "Time Period Information of Source Input"))
        self.label_38.setText(_translate("Form", "Beginning Date (YYYYMMDD)"))
        self.label_39.setText(_translate("Form", "End Date (YYYYMMDD)"))
        self.label_5.setText(_translate("Form", "Currentness Reference"))
        self.fgdc_srccurr.setItemText(0, _translate("Form", "ground condition"))
        self.fgdc_srccurr.setItemText(1, _translate("Form", "observed"))
        self.fgdc_srccurr.setItemText(2, _translate("Form", "publication date"))
        self.label_7.setText(_translate("Form", "Abbreviation / Short Name for the Input Data   (Updated as Needed)"))
        self.label_10.setText(_translate("Form", "1:"))
        self.label_9.setText(_translate("Form", "Source Scale"))
        self.label_8.setText(_translate("Form", "Contribution of Source Input   (Update as Needed)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

