# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'status.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(268, 117)
        Form.setMinimumSize(QtCore.QSize(268, 0))
        Form.setMaximumSize(QtCore.QSize(268, 16777215))
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.fgdc_status = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_status.sizePolicy().hasHeightForWidth())
        self.fgdc_status.setSizePolicy(sizePolicy)
        self.fgdc_status.setStyleSheet("")
        self.fgdc_status.setObjectName("fgdc_status")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fgdc_status)
        self.verticalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.fgdc_status)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.fgdc_progress = QtWidgets.QComboBox(self.fgdc_status)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.fgdc_progress.setFont(font)
        self.fgdc_progress.setEditable(True)
        self.fgdc_progress.setObjectName("fgdc_progress")
        self.fgdc_progress.addItem("")
        self.fgdc_progress.addItem("")
        self.fgdc_progress.addItem("")
        self.verticalLayout_2.addWidget(self.fgdc_progress)
        self.label_3 = QtWidgets.QLabel(self.fgdc_status)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.fgdc_update = QtWidgets.QComboBox(self.fgdc_status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fgdc_update.sizePolicy().hasHeightForWidth())
        self.fgdc_update.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.fgdc_update.setFont(font)
        self.fgdc_update.setEditable(True)
        self.fgdc_update.setObjectName("fgdc_update")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.fgdc_update.addItem("")
        self.verticalLayout_2.addWidget(self.fgdc_update)
        self.verticalLayout.addWidget(self.fgdc_status)

        self.retranslateUi(Form)
        self.fgdc_update.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.fgdc_status.setTitle(_translate("Form", "Data Status and Update Plans"))
        self.label_2.setText(_translate("Form", "Status"))
        self.fgdc_progress.setCurrentText(_translate("Form", "Complete"))
        self.fgdc_progress.setItemText(0, _translate("Form", "Complete"))
        self.fgdc_progress.setItemText(1, _translate("Form", "In Work"))
        self.fgdc_progress.setItemText(2, _translate("Form", "Planned"))
        self.label_3.setText(_translate("Form", "Update Plans"))
        self.fgdc_update.setItemText(0, _translate("Form", "Continually"))
        self.fgdc_update.setItemText(1, _translate("Form", "Daily"))
        self.fgdc_update.setItemText(2, _translate("Form", "Weekly"))
        self.fgdc_update.setItemText(3, _translate("Form", "Monthly"))
        self.fgdc_update.setItemText(4, _translate("Form", "Annually"))
        self.fgdc_update.setItemText(5, _translate("Form", "Unknown"))
        self.fgdc_update.setItemText(6, _translate("Form", "As needed"))
        self.fgdc_update.setItemText(7, _translate("Form", "Irregular"))
        self.fgdc_update.setItemText(8, _translate("Form", "None planned"))

