# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'taxonomy2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Taxonomy(object):
    def setupUi(self, Taxonomy):
        Taxonomy.setObjectName("Taxonomy")
        Taxonomy.resize(565, 416)
        Taxonomy.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Taxonomy)
        self.verticalLayout_2.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.fgdc_taxonomy = QtWidgets.QGroupBox(Taxonomy)
        self.fgdc_taxonomy.setObjectName("fgdc_taxonomy")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.fgdc_taxonomy)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.fgdc_taxonomy)
        self.label_3.setMinimumSize(QtCore.QSize(0, 20))
        self.label_3.setStyleSheet("font: italic;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.rbtn_yes = QtWidgets.QRadioButton(self.fgdc_taxonomy)
        self.rbtn_yes.setAutoFillBackground(True)
        self.rbtn_yes.setChecked(False)
        self.rbtn_yes.setObjectName("rbtn_yes")
        self.horizontalLayout.addWidget(self.rbtn_yes)
        self.rbtn_no = QtWidgets.QRadioButton(self.fgdc_taxonomy)
        self.rbtn_no.setAutoFillBackground(True)
        self.rbtn_no.setChecked(True)
        self.rbtn_no.setObjectName("rbtn_no")
        self.horizontalLayout.addWidget(self.rbtn_no)
        self.main_layout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_layout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(6, -1, -1, -1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.main_layout.addLayout(self.horizontalLayout_3)
        self.frame_included_species = QtWidgets.QFrame(self.fgdc_taxonomy)
        self.frame_included_species.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_included_species.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_included_species.setObjectName("frame_included_species")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_included_species)
        self.verticalLayout.setContentsMargins(5, 5, 5, 2)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(9, -1, 9, 3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.btn_search = QtWidgets.QPushButton(self.frame_included_species)
        self.btn_search.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("")
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_4.addWidget(self.btn_search)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.main_layout.addWidget(self.frame_included_species)
        self.groupBox = QtWidgets.QGroupBox(self.fgdc_taxonomy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.taxon_kws = QtWidgets.QWidget(self.groupBox)
        self.taxon_kws.setObjectName("taxon_kws")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.taxon_kws)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4.addWidget(self.taxon_kws)
        self.main_layout.addWidget(self.groupBox)
        self.taxoncl_scrollarea = QtWidgets.QScrollArea(self.fgdc_taxonomy)
        self.taxoncl_scrollarea.setWidgetResizable(True)
        self.taxoncl_scrollarea.setObjectName("taxoncl_scrollarea")
        self.taxoncl_contents = QtWidgets.QWidget()
        self.taxoncl_contents.setGeometry(QtCore.QRect(0, 0, 549, 291))
        self.taxoncl_contents.setObjectName("taxoncl_contents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.taxoncl_contents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.taxoncl_scrollarea.setWidget(self.taxoncl_contents)
        self.main_layout.addWidget(self.taxoncl_scrollarea)
        self.verticalLayout_3.addLayout(self.main_layout)
        self.verticalLayout_2.addWidget(self.fgdc_taxonomy)

        self.retranslateUi(Taxonomy)
        QtCore.QMetaObject.connectSlotsByName(Taxonomy)

    def retranslateUi(self, Taxonomy):
        _translate = QtCore.QCoreApplication.translate
        Taxonomy.setWindowTitle(_translate("Taxonomy", "Form"))
        Taxonomy.setToolTip(_translate("Taxonomy", "test docstring"))
        self.fgdc_taxonomy.setTitle(_translate("Taxonomy", "Taxonomy"))
        self.label_3.setText(_translate("Taxonomy", "Does this record contain biological data about particular species or other  taxons?"))
        self.rbtn_yes.setText(_translate("Taxonomy", "Yes"))
        self.rbtn_no.setText(_translate("Taxonomy", "No"))
        self.btn_search.setText(_translate("Taxonomy", "Add Items from ITIS"))
        self.groupBox.setTitle(_translate("Taxonomy", "Taxonomic Keywords"))

